### ISSUE TITLE
Message attempt serde error in Rust library

### ISSUE THREAD

**Issue by ksindi** [svix/svix-webhooks#1009]
## Bug Report

The Svix Rust library does not deserialize Svix's response correctly causing an exception. I suspect the issue is because status and responseStatusCode JSON are integers whereas Rust tries to deserialize strings into their respective structs.

### Version

Svix 1.6.0

### Platform

Linux/Debian

### Description

Reproduction steps:

```rust
use std::env;

use svix::api::Svix;

#[tokio::main]
async fn main() {
    let auth_token = env::var("SVIX_AUTH_TOKEN")
        .unwrap_or_else(|_| "my-api-key".to_string());

    let svix = Svix::new(auth_token, None);

    let app_uid = "some-app-uid";
    let endpoint_id = "some-endpoint-id";

    let list_message_attempt_out = svix
        .message_attempt()
        .list_by_endpoint(app_uid.to_string(), endpoint_id.to_string(), None)
        .await;

    // Print the result
    match list_message_attempt_out {
        Ok(list_message_attempt_out) => println!("{:#?}", list_message_attempt_out),
        Err(e) => println!("Error: {}", e),
    }
}
```

Error:
```
Error: error in serde: expected value at line 1 column 131
```

Note this assumes the list is not empty and there are message attempts.

**Comment by svix-nick** [comment]
I believe I've found the issue. We should have a fix out soon.

**Comment by svix-nick** [comment]
[Svix 1.7.0](https://github.com/svix/svix-webhooks/releases/tag/v1.7.0) has been released which includes the fix for this issue. The `MessageStatus`, `MessageAttemptTriggerType`, and `StatusCodeClass` enums now serialize and deserialize properly.
