### ISSUE TITLE
Golang: Add constructor to the `NullableInt32` type used for setting `RateLimit`.

### ISSUE THREAD

**Issue by rkuprov** [svix/svix-webhooks#1017]
### Motivation
Right now, `NullableString()` function is exposed (used to populate `uid` field in `Application` and `Endpoint`). However, a similar function is missing for `RateLimit`. The `NullableInt32` type is internal and is unavailable for use w/out the constructor. So, it is impossible to populate the `RateLimit` field when using the golang package.

### Proposal
Add a `NullableInt32(*int32) *openapi.NullableInt32` function.

It would literally be just a copy of `NullableString`, but with a pointer argument. 
### Alternatives

There's really not much to it. It was definitely needed to be done and, it seems, just fell through the cracks.

**Comment by tasn** [comment]
Fixed in the linked PR.
