### ISSUE TITLE
Change serde/serde_derive to >= 1.0.184 to avoid precompiled binaries

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#1042]
Serde started shipping pre-compiled binaries, which is obviously not a good thing... So we'll have to pin to an old version until they undo this.

Also need to pin serde derive.

Ref: https://github.com/serde-rs/serde/issues/2538

**Comment by svix-daniel** [comment]
Version 1.0.184 removes this binary blob. See https://github.com/serde-rs/serde/releases/tag/v1.0.184

**Comment by tasn** [comment]
OK, make  v1.0.184 a minimum req instead.

**Comment by tasn** [comment]
Add to cargo-deny if not too hard.
