### ISSUE TITLE
ApplicationIn struct is not exported from Go client

### ISSUE THREAD

**Issue by ynonevermile** [svix/svix-webhooks#1043]
Hey team,
Nice to meet you all.
I’ve started trying to use Svix with Golang.
When trying to create my first message, it looks like there’s an issue with the package where the MessageIn needs an ApplicationIn struct in the input, but that struct is defined in the unexported openapi package (it’s nested within the internal directory).
The Golang compiler is rightfully refusing to compile the following code:
```go
	s.SvixClient.Message.CreateWithOptions(ctx, appId, &svix.MessageIn{
		Application: &svix.ApplicationIn{
			Name: appId,
		},
		EventId:                *svix.NullableString(svix.String(idempotencyKey)),
		EventType:              string(eventType),
		Payload:                nil,
		PayloadRetentionPeriod: nil,
	}, &svix.PostOptions{
		IdempotencyKey: svix.String(idempotencyKey),
	})
```
due to the expected error
```
Cannot use '&svix.ApplicationIn{ Name: appId, }' (type *ApplicationIn) as the type *ApplicationIn
```

**Comment by giautm** [comment]
I saw it already exported here: https://github.com/svix/svix-webhooks/blob/a0bf1412a333874827f1ab2e97fb4b3bc446f2af/go/application.go#L11

**Comment by tasn** [comment]
@giautm, I think the problem is that while it's exported, we are maybe using the wrong type in MessageIn so that it can't use what we pass. I thought these types were just the same as they are re-exports, so I thought it would be fine. I know nothing about Golang though (need to wait for the team to check it out tomorrow).

**Comment by ynonevermile** [comment]
@giautm it's exactly as @tasn mentioned.
The `MessageIn` struct is defined inside the openapi (internal) package, with the following types that are also internal:

```go
// MessageIn struct for MessageIn
type MessageIn struct {
	Application *ApplicationIn `json:"application,omitempty"`
	// List of free-form identifiers that endpoints can filter by
	Channels []string `json:"channels,omitempty"`
	// Optional unique identifier for the message
	EventId NullableString `json:"eventId,omitempty"`
	// The event type's name
	EventType string `json:"eventType"`
	Payload map[string]interface{} `json:"payload"`
	PayloadRetentionPeriod *int64 `json:"payloadRetentionPeriod,omitempty"`
}
```

Since the `ApplicationIn` here is an internal struct defined in the package `openapi`, the Go compiler will not accept the exported struct in its place.

**Comment by giautm** [comment]
Ah, the export type should be the alias of the internal. So, instead of `type ApplicationIn openapi.ApplicationIn`. It must be `type ApplicationIn = openapi.ApplicationIn`. :D

**Comment by giautm** [comment]
Hey @tasn, I just open a PR for the fix. I hope it helps. :)
