### ISSUE TITLE
Create Endpoint via Dotnet sdk doesn't set uid

### ISSUE THREAD

**Issue by irfn** [svix/svix-webhooks#1114]
## Bug Report
While creating Endpoints in an Application from a dotnet codebase I am not able to set uid in create call.
This is specific the the Dotnet lib as I was able to set `uid` from ruby, svix cli etc. 

### Version
Svix Web hooks Server via docker image v1.13
Dotnet package Svix 1.13.0

### Platform
macOS dotnet framework version 7.0.100
Svix in Docker

### Description
Here I tried both `svix.Endpoint.Create` and `svix.Endpoint.CreateAsync` and rest of the attributes are being set.
```
svix.Endpoint.Create(applicationOut.Id ,new EndpointIn( 
                description: "A Sample Endpoint",
                uid: endPointUid,
                url: endPointUrl,
                version: 1
            ), endPointUid);
```
I tried both with using endPointUid as idempotency key as well.

As mentioned before this seems like an issue in the dotnet sdk.

**Comment by tasn** [comment]
Whoops, missed this. We'll take a look next week!

**Comment by svix-james** [comment]
@irfn I'm not able to reproduce this. Is it possible you may have created the endpoint with the idempotency key specified, then later went back and attempted to create with a uid with the idempotency key specified?

Can you try to reproduce this using a new endpoint/uid?

**Comment by irfn** [comment]
@svix-james I did try with completely new endpoints. In any case I'll attempt this again tomorrow and update here.

**Comment by irfn** [comment]
@svix-james Apologies for  logging the ticket. 

A fresh example and not reusing the IDs etc could not reproduce the issue.
https://github.com/irfn/CSharpSvixDemo/
I am closing this issue and I will report back In case I note the issue in some scenario.
