### ISSUE TITLE
svix-bridge: Invalid Svix secret: InvalidSecret(InvalidByte(5, 61))

### ISSUE THREAD

**Issue by davehorner** [svix/svix-webhooks#1130]
## Bug Report
`cargo run --no-default-features --features gcp-pubsub,rabbitmq,redis,sqs -- --cfg-file svix-bridge.example.receivers.yaml
`

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.81s
     Running `target\debug\svix-bridge.exe --cfg-file svix-bridge.example.receivers.yaml`
2023-11-21T17:18:20.519305Z  INFO svix_bridge: starting
2023-11-21T17:18:20.519894Z  WARN svix_bridge: No senders configured.
2023-11-21T17:18:20.519926Z  INFO svix_bridge: Starting JS Transformation Workers: 4
thread '2023-11-21T17:18:20.520034Z ERROR common_metrics_collector: svix_bridge: Unable to get allocator stats mibs: metric collection is not supported
main' panicked at svix-bridge\src\webhook_receiver\types.rs:65:67:
Invalid Svix secret: InvalidSecret(InvalidByte(5, 61))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\svix-bridge.exe --cfg-file svix-bridge.example.receivers.yaml` (exit code: 101)
```

### Version

```
cargo tree | rg svix
svix-bridge v1.14.0 (C:\w\rust\svix-webhooks\bridge\svix-bridge)
├── svix-bridge-plugin-queue v0.1.0 (C:\w\rust\svix-webhooks\bridge\svix-bridge-plugin-queue)
│   ├── omniqueue v0.1.0 (https://github.com/svix/omniqueue-rs?rev=247904053bcf90cf693df4429092923bf97770eb#24790405)
│   ├── svix-bridge-types v0.1.0 (C:\w\rust\svix-webhooks\bridge\svix-bridge-types)
│   │   ├── svix v0.85.1
├── svix-bridge-types v0.1.0 (C:\w\rust\svix-webhooks\bridge\svix-bridge-types) (*)
├── svix-ksuid v0.7.0
svix-bridge-plugin-queue v0.1.0 (C:\w\rust\svix-webhooks\bridge\svix-bridge-plugin-queue) (*)
svix-bridge-types v0.1.0 (C:\w\rust\svix-webhooks\bridge\svix-bridge-types) (*)
```

### Platform

win11x64

### Description

Just running the examples;  the senders.xml looks to be working (continues to run and events stream to console).  receivers panics.

**Comment by svix-onelson** [comment]
The endpoint secrets are fake in the example file, e.g. `whsec_XXXXX=`.

You'd need to register an endpoint in svix, pointing to your running bridge, then put the secret for that endpoint in your bridge config.

You'd also need to be running a queue matching the output.

I think more than anything we need to do a pass on the config parser so it can make suggestions when it reports failures rather than just bubbling up a panic.

**Comment by davehorner** [comment]
bubbling up a panic seems like an ok approach but we lose context of where it happened in the config which is unfortunate.

I didn't run the containers and I expected issues.
```
main' panicked at svix-bridge\src\webhook_receiver\types.rs:65:67:
Invalid Svix secret: InvalidSecret(InvalidByte(5, 61))
```

I didn't expect a panic on a invalid secret.
Running the bridge with no arguments panics with "config file path".

panics are fine; just need to spend some more time with the code.
