### ISSUE TITLE
getting exceptions and malformed json posting or putting event types with attached schemas

### ISSUE THREAD

**Issue by nerdlark** [svix/svix-webhooks#1131]
### Version

1.14.0

### Platform

JVM/Windows

### Description

We're using svix java sdk. The problem is that we're getting exceptions posting or putting event types as soon as we attach schemas. It seems like the map-type that needs to be attached is not serialized in a proper way internally.

**Comment by svix-james** [comment]
@nerdlark I just noticed that the API examples in our docs are completely wrong. However, if I instantiate a proper HashMap, it works correctly for me in code, i.e., something like:

```
		EventTypeIn eventType = new EventTypeIn()
			.name("user.signup")
			.description("A user has signed up")
			.archived(false)
			.featureFlag("cool-new-feature")
			.schemas(
				Map.of(
					"1", Map.of(
						"description", "An invoice was paid by a user",
						"properties", Map.of(
							"invoiceId", Map.of(
								"description", "The invoice id",
								"type", "string")
							),
							"userId", Map.of(
								"description", "The user id",
								"type", "string"),
							"required", List.of("invoiceId", "userId"),
							"title", "Invoice Paid Event",
							"type", "object"
						)
				)
			);
```

I'm not immediately sure why the example is broken, but I'll look into fixing it.

**Comment by svix-james** [comment]
If the above is not relevant to your issue @nerdlark , please post a reproducible example if possible.

**Comment by svix-james** [comment]
Note that I have updated our API documentation to no longer show the invalid examples.

**Comment by tasn** [comment]
I believe this was a documentation issue (that's now fixed), so closing it unless it's still an issue.
