### ISSUE TITLE
The Svix Python SDK does not have built in support for the documented health check endpoint

### ISSUE THREAD

**Issue by BarakW** [svix/svix-webhooks#1135]
### Version

1.13 (though the code from 1.14 looks the same)

### Platform

Linux 64-bit ARM

### Description

The OpenAPI spec [here](https://api.svix.com/api/v1/openapi.json) shows that the SDK's include support for the health check endpoint, but this is not the case for at least the Python 1.13.x or [1.14.x versions](https://github.com/svix/svix-webhooks/blob/25ef31aef66972bb6d82e77280adc3aae188465c/python/svix/api.py). I also checked the latest Rust and Kotlin SDK's out of curiosity and they don't seem to include this either. It's not too difficult to work around this since it is an unauthenticated endpoint, but it would be nice to not have to skip using the Svix SDK for some calls.

### Proposed solution (edit by @tasn)
Let's just remove it from the code samples as suggested by @BarakW.

This section was added by @tasn

**Comment by tasn** [comment]
I think we don't have it in any of the libraries, it being documented sounds like a mistake. I didn't even realize we exposed the health check in the docs! What are you looking to use it for from Python? People usually implement health checks with cURL / other CLI utility.

Anyhow, I'll ask the team to take a look, sounds like a silly oversight, thanks for the report!

**Comment by tasn** [comment]
Hey @BarakW, I just wanted to follow up on my question about using it from Python. Why is this needed?

**Comment by BarakW** [comment]
@tasn in my case I'm using it for a programmatic service health check

**Comment by tasn** [comment]
Gotcha, thanks for the info! We can probably add it, I wonder if this will just be confusing for people to have it.

I assume you can work around it in the meantime by making the HTTP call directly just for this one, right? There aren't any params or anything, so a lot of the nice things about the libs don't really matter for this API call, right?

**Comment by BarakW** [comment]
Yeah I just worked around it by not using the SDK. I think it's actually fine to not include it, it's more of a nitty bug report TBF since it's just a bit confusing for the docs to show that it's available in the SDK when it isn't. I spent around 30 mins trying to find the `health` method call initially 😅. I would say it's just as good to remove the SDK call examples from the docs

**Comment by tasn** [comment]
Yes, that was my initial thought, but then I swung the other way, though I think I'm back to just removing the code samples from the docs! Thanks for the feedback!
