### ISSUE TITLE
Bump rust lib to Hyper 1.0

### ISSUE THREAD

**Issue by aldofunes** [svix/svix-webhooks#1146]
It's actually about the libs

## Feature Request

Upgrade axum to 0.7

### Motivation

I have an axum server that uses svix, both as an emitter and a consumer. With the recent changed to 1.0 of the hyper and http crates, a bunch of breaking changes were introduced in the ecosystem. Axum's 0.7 version now supports these 1.0 releases. However, since it uses a different http create version, the validation of webhooks fails due to the HeaderMap's version difference in the function signature.

I have put a lot of effort into migrating our codebase to axum 0.7 and this is the last piece of the puzzle.

### Proposal

Having skimmed through the lib's code, this should not introduce breaking changes, but will probably require custom feature flags like `axum06` and `axum07`.

Since I'm blocked, and you guys are probably busy, I can do these changes and submit a PR; but I might need some guidance into any standards or ways of doing things you guys have.

### Alternatives

Te alternative is to go back to 0.6, which will work for the time being, but I'm assuming this will eventually be needed

**Comment by tasn** [comment]
It sounds like you're referring to the Rust lib, not the server itself, right?

**Comment by aldofunes** [comment]
Yes, the rust lib.

Having just gone through the upgrade on a server with a pretty similar setup (axum+aide), I know the server will be a huge undertaking.

I understand if you guys are planning to upgrade the whole think in one go

**Comment by tasn** [comment]
Good to know it's a huge undertaking. We were going to do it but the changelog looked significant so we decided to defer it for a bit. :)

We can probably upgrade the libs for now anyway and worry about the server at a later stage.

**Comment by tasn** [comment]
Quick glance: one of our deps (Reqwest) is incompatible with Hyper 1.0 still.
We can take a look whether using the OpenAPI generator with Hyper works when forcing it to use Hyper 1.0.

**Comment by tasn** [comment]
Hey @aldofunes, you mentioned you'd be open to opening a PR, is it still the case? Just need to update the openapi spec generator to generate Hyper instead of reqwest, and then up the dep requirements of Hyper to >=1 and hope it works. :P

**Comment by Srlion** [comment]
Any updates on this? at least update the lib to be able to use `webhook.verify`

**Comment by tasn** [comment]
If we don't hear back from @aldofunes about this, we'll take a jab at it next week. Thanks for bumping the issue!

**Comment by Srlion** [comment]
@tasn Any news?

**Comment by tasn** [comment]
We started looking at it last week. It looks like some of our dependencies, namely the AWS Rust SDK depends on Hyper 0.10 (tracking ticket: https://github.com/awslabs/aws-sdk-rust/issues/977).

Though we'll figure out a way to support both. We have a new team member joining the team on Thursday and I plan for him to fix it.
