### ISSUE TITLE
Why use threetenbp instead of java time for time

### ISSUE THREAD

**Issue by Burane** [svix/svix-webhooks#1161]
### Motivation

When using threetenbp instead of java time it force to have all payload objects you want to send in a webhook message to use threetenbp.

### Proposal
In [java/openapi-generator-config.json](https://github.com/svix/svix-webhooks/blob/main/java/openapi-generator-config.json) add ` "dateLibrary": "java8"`
So it will use java time instead of  threetenbp

**Comment by tasn** [comment]
More from Slack:
> I dont think there is an other way than support 2 version of the lib :confused:
> Do you have data for how many use pre-java 8 version (who will be 10 years old in a few months)

I think this is a great change and we should do it.
