### ISSUE TITLE
Support URLs without trailing slashes?

### ISSUE THREAD

**Issue by mderriey** [svix/svix-webhooks#1254]
## Feature Request

_Opening an issue as requested by @tasn in <https://github.com/svix/svix-webhooks/discussions/1252>_.

Svix API endpoints all have a trailing slash, for example `/api/v1/app/{app_id}/msg/`.

### Motivation

- It's valid, but it's not common in my experience.
- It also caught us twice while we were playing around with the API via Postman and hand-written code where we didn't include it out of habit and got 404s back.
- Some tools don't support trailing slashes; we used Microsoft's Kiota to generate a .NET API client, and during generation it removed the trailing slashes (see <https://github.com/microsoft/kiota/issues/4291>).

### Proposal

The proposal is to:

- Support URLs both with and without the trailing slashes so it's a backwards-compatible change.
- Make URLs without the trailing slash "default", e.g. they should be the ones that appear in the OpenAPI document.

### Alternatives

N/A

**Comment by tasn** [comment]
Is where any reason why not just support both?
