### ISSUE TITLE
The C# library is missing the new app portal interface that supports the feature flags

### ISSUE THREAD

**Issue by FlorianHoornaar** [svix/svix-webhooks#1272]
### Motivation

See [this code example](https://docs.svix.com/event-types#event-type-feature-flags)
```
var svix = new SvixClient("AUTH_TOKEN", new SvixOptions("https://api.svix.com/"));
var dashboard = await svix.Authentication.AppPortalAccessAsync("app_Xzx8bQeOB1D1XEYmAJaRGoj0", new AppPortalAccessIn{
    featureFlags: new string[] {"beta-feature-a"}
});
// A URL that automatically logs user into the dashboard
Console.WriteLine(dashboard.Url)
```

The [SvixClient ](https://github.com/svix/svix-webhooks/blob/49a8184baeeb1f1e72968533e97eccb7a4030cf1/csharp/Svix/SvixClient.cs)class has a property IAuthentication Authentication .  However the [IAuthentication](https://github.com/svix/svix-webhooks/blob/49a8184baeeb1f1e72968533e97eccb7a4030cf1/csharp/Svix/Abstractions/IAuthentication.cs) interface does not have a method AppPortalAccessAsync.

It does have a method GetDashboardAccessAsync which works well, but does not allow to pass feature flags.

### Proposal

See [this slack thread](https://svixcommunity.slack.com/archives/C031WPPNTUZ/p1710236064439499)

**Comment by tasn** [comment]
Whoops, missed this. Will get this added asap, sorry for the delay!
