### ISSUE TITLE
Add Source Map to Package

### ISSUE THREAD

**Issue by sm-fm** [svix/svix-webhooks#1299]
### Version

svix 1.21.0
svix-react 1.11.0

### Description

The source maps need to added to the package. I currently have 157 warnings whenever I build my client because of the lack of source mapping. I've seen other people bring up this issue as well.

I know I can turn source mapping off, but that makes debugging in production more difficult.

Please update the package to contain the source maps so these warnings will go away.

**Comment by tasn** [comment]
Whoops, sorry about that. Also sorry for missing this ticket. Will take a look asap!

**Comment by svix-lucho** [comment]
I think the reason why you're seeing such warnings is that in `svix` we are publishing the package with `sourceMaps` but without the corresponding TS files. I'll send a PR to publish `src` as well as `dist`, so the TS files are in the location pointed by the source maps. 

`svix-react` does not publish sourceMaps (yet), so it shouldn't have the same issue.
