### ISSUE TITLE
SVIX_FOLLOW_REDIRECTS = FALSE

### ISSUE THREAD

**Issue by ben74** [svix/svix-webhooks#1307]
### Motivation

When using Svix in order to send payloads to the external world ( user can change his endpoint and gets messages results ) we won't let user use redirections in order to probe our inner infrastructure

### Proposal

SVIX_FOLLOW_REDIRECTS = FALSE
-> results in CURLOPT_FOLLOWLOCATION=FALSE

### Alternatives

SVIX_PROXY=forwarder:8080
then how to configure a forwarder with redirections=off ???

**Comment by tasn** [comment]
We already don't follow redirects. What are you asking for specifically?

**Comment by ben74** [comment]
Damn you're right I haven't notice it before, thanks

**Comment by tasn** [comment]
Great, closing this ticket. Thanks! :)
