### ISSUE TITLE
Go library is missing `withMsg` parameter for a few endpoints

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#1381]
```
listResponseMessageAttemptOut, err := svixClient.MessageAttempt.ListByEndpoint(ctx, "app_id", "endpoint_id", nil)
```
This is missing `withMsg` in `MessageAttemptListOptions`.

**Comment by tasn** [comment]
Let's also review the rest of the attempt listing functions to make sure it's there when needed.

**Comment by svix-onelson** [comment]
https://github.com/svix/svix-webhooks/pull/1387 exposes with_msg in `MessageAttempt.ListByEndpoint`.

I grepped for `with_msg` in the rest of the go client code, and this one was the only place it showed up. There might be more params in the private API that are missing from public, but this one looks covered by the pending PR.

I'll try and do a more loose survey, eyeballing the various `-ListOption` types, before I close this issue out. Hopefully if there's a gap it'll jump out.

**Comment by svix-onelson** [comment]
I finished my audit. There's a handful of PRs raised to fill the gaps. I wonder what we can do to automate this to the point where CI flags these unused-but-should-be-used params in the internal API?
