### ISSUE TITLE
C# SDK: parameters passed in wrong order in RotateSecretAsync method

### ISSUE THREAD

**Issue by robertjamesharrison** [svix/svix-webhooks#1407]
See below code - `appId` should be passed first, then `endpointId`. This currently results in a confusing 'application not found' error.

https://github.com/svix/svix-webhooks/blob/837ffddd13a85cc509ee94d7b0c001961df56479/csharp/Svix/Endpoint.cs#L418

**Comment by tasn** [comment]
Whoops, thanks! We'll take a look ASAP.

**Comment by tasn** [comment]
Fixed. It'll be available in the next lib relesae.
