### ISSUE TITLE
[server] delete event-type does not delete anything

### ISSUE THREAD

**Issue by michabbb** [svix/svix-webhooks#1457]
## Bug Report

docker: svix/svix-server:v1.36.0

call: DELETE http://xxxxxxxxx:8071//api/v1/event-type/order.delivered/?expunge=true
response: 204

but a list event-types always shows:

```json
{
    "data": [
        {
            "name": "item.delivered",
            "description": "an item has been deliverd",
            "archived": false,
            "deprecated": false,
            "schemas": null,
            "createdAt": "2024-09-28T19:43:38.872620Z",
            "updatedAt": "2024-09-28T19:43:38.872620Z",
            "featureFlag": null
        },
        {
            "name": "order.delivered",
            "description": "an order has been deliverd",
            "archived": true,
            "deprecated": false,
            "schemas": null,
            "createdAt": "2024-09-28T18:01:01.953404Z",
            "updatedAt": "2024-09-28T20:08:19.369679Z",
            "featureFlag": null
        }
    ],
    "iterator": "order.delivered",
    "prevIterator": "-item.delivered",
    "done": true
}
``` 

so whatever I do, I cannot delete the "order.delivered" event-type 😢 
please let me know if I am doing something wrong.

thanks!

**Comment by tasn** [comment]
It changes it to "archived". You need to pass `expunge` in order to fully remove it: https://api.svix.com/docs#tag/Event-Type/operation/v1.event-type.delete

**Comment by michabbb** [comment]
@tasn 

![image](https://github.com/user-attachments/assets/77e4032e-fe7a-4452-a3fd-c3d18bea708d)

is that wrong ????

**Comment by tasn** [comment]
I missed that. It looks like another feature that was built in SaaS but hasn't been backported to OSS.

**Comment by michabbb** [comment]
@tasn so... is it save to delete it directly in the database ? or are there any dependencies ??

**Comment by tasn** [comment]
You can delete it in the database, it shouldn't be a problem. Though we'll also fix it first thing next week!
