### ISSUE TITLE
Not supporting Redis ElasticCache cluster mode

### ISSUE THREAD

**Issue by sanjaywinjit** [svix/svix-webhooks#1458]
thread 'main' panicked at /app/svix-server/src/queue/redis.rs:155:17:
backend-1  | error creating consumer group or stream: Moved

**Comment by svix-jplatte** [comment]
In general, Redis cluster isn't supported in the OSS version at the moment. I'll put this up for discussion.

**Comment by tasn** [comment]
Exactly what @svix-jplatte said, it's supported.
