### ISSUE TITLE
code: 'ERR_REQUIRE_ESM'

### ISSUE THREAD

**Issue by ZONGMENG-kaito** [svix/svix-webhooks#1505]
## Bug Report

I use `svix` in my npm project, but when I use the latest version, I got an error and the error code is `code: 'ERR_REQUIRE_ESM'`
### Version

Latest version

### Platform
Mac os

### Description

I believe is because this dependency's upgrade: https://github.com/svix/svix-webhooks/blob/main/javascript/package.json#L32, upgrade to `2.0.0`, which make the `@stablelib/base64` to be ESM only: https://github.com/StableLib/stablelib/blob/master/packages/base64/package.json#L6

![Image](https://github.com/user-attachments/assets/c86becd7-0c96-4899-ad31-bc2f320a1f36)

@svix-onelson I likely found the upgrade PR was made from you, would you mind downgrading or fixing it? Thanks a lot.

**Comment by IbrahimMohammed47** [comment]
Until they fix it, I found that version `1.37.0` is the latest one using `@stablelib/base64` version 1
So you can use this in you package.json for now `"svix": "~1.37.0"` until we have a fix

**Comment by ZONGMENG-kaito** [comment]
> Until they fix it, I found that version `1.37.0` is the latest one using `@stablelib/base64` version 1 So you can use this in you package.json for now `"svix": "~1.37.0"` until we have a fix or you may want to migrate your project to be `esm`

Thanks for your kinda reply, actually I am using this package: https://www.npmjs.com/package/@privy-io/server-auth which uses `svix` as a dep, so I finally got this error. I will try to modify my project to `esm`.

**Comment by tasn** [comment]
I wonder if we should just downgrade the base64 lib. Thanks for the report!

**Comment by ZONGMENG-kaito** [comment]
> I wonder if we should just downgrade the base64 lib. Thanks for the report!

Thanks, Tom, I strongly recommend that downgrade it to `^1.0.0`, think this way. should be the easiest way to fix it?

**Comment by tasn** [comment]
Yeah, it's probably the right call (as long as there are no security issues or other incompatibilities). I wonder why upstream broke things this way. :|

**Comment by ZONGMENG-kaito** [comment]
> Yeah, it's probably the right call (as long as there are no security issues or other incompatibilities). I wonder why upstream broke things this way. :|

Hope to see a quick rollback version, :D.

**Comment by svix-onelson** [comment]
Hi folks, the downgrade for `@stablelib/base64` to the 1.x line landed moments ago. This should be resolved in the upcoming release.

**Comment by ZONGMENG-kaito** [comment]
> Hi folks, the downgrade for `@stablelib/base64` to the 1.x line landed moments ago. This should be resolved in the upcoming release.

Thanks for your working, do we plan to release a new version shortly?

**Comment by svix-onelson** [comment]
@ZONGMENG-kaito I anticipate a release tomorrow (Nov 9th).

**Comment by ZONGMENG-kaito** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/119031446?s=64&amp;u=3793ba0dda8f91d974d06ecef04a415bb4c3e60b&amp;v=4">@ZONGMENG-kaito](https://github.com/ZONGMENG-kaito) I anticipate a release tomorrow (Nov 8th).

Not yet, I will test it soon. Thanks for your work

**Comment by ZONGMENG-kaito** [comment]
> There was a release already, did it not fix it for you?

Yes, it's fixed now, big thanks to all of you.
