### ISSUE TITLE
Replace `unwrap` by `expect`, later by proper error handling

### ISSUE THREAD

**Issue by SuperFluffy** [svix/svix-webhooks#280]
## Bug Report

I am filing this as a bug report because this is very likely to show up sooner or later and will cause confusion ("where did this panic occur and why?!")

`expect` with a message is preferred over `unwrap` (if panics are intended and the state is unrecoverable) or replaced by proper error handling. Looking at all code here and below: https://github.com/svix/svix-webhooks/blob/3bee36df5a6977b64c66275b475159857bca5e5c/server/svix-server/src/main.rs#L57

### Version

At least `0.51`.

**Comment by tasn** [comment]
Great suggestion, thanks a lot!
