### ISSUE TITLE
Automatically build and release images to docker (in CI)

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#281]

**Comment by codetheweb** [comment]
We're currently trying to run a local instance of Svix during our tests, so this would be really helpful. :)

Version 0.51.0 (the latest image) is currently failing with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Execute(Database(PgDatabaseError { severity: Error, code: "3F000", message: "no schema has been selected to create in", detail: None, hint: None, position: Some(Original(29)), where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("namespace.c"), line: Some(497), routine: Some("RangeVarGetCreationNamespace") }))'
```

(I assume something to do with running migrations, but `svix-server migrate` isn't available in 0.51.0.)

**Comment by tasn** [comment]
Just pushed a new docker image, sorry about that. I think we also improved error messages since 0.51.0. :)

Migration should run automatically in release builds though, so I don't think it's the lack of the migration command that's causing issue. The idea behind adding it was to just bring more control to people who want to manage the migration process.

**Comment by tasn** [comment]
@codetheweb, I just had a chat with one of our customers that also used the docker, for him it was literally just about running: `docker-compose up`, and everything worked.

How are you running Svix?

**Comment by tasn** [comment]
I'm no PG expert, but altering the role like this seems reasonable, no?

Anyhow, if theres' an issue please open another ticket, yeah. :P
