### ISSUE TITLE
Update to the last version of svix-ksuid and drop chrono

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#284]
The current version relies on Chrono which is deprecated so rust-ksuid switched away from it. We should do too.

- Once we switch away from it, we can merge in #285.
- We also need to update SeaORM to a version that doesn't depend on Chrono (is there one already?) - It's merged: https://github.com/SeaQL/sea-orm/pull/602

**Comment by tasn** [comment]
Weepee, seaorm merged the time change: https://github.com/SeaQL/sea-orm/pull/602

**Comment by tasn** [comment]
@svix-daniel, new seaorm release!

**Comment by svix-daniel** [comment]
Waiting on the next `sqlx` release which updates the `time` crate  to `0.3.x`.
https://github.com/launchbadge/sqlx/issues/1413

**Comment by svix-james** [comment]
chrono forever!!!!!!
