### ISSUE TITLE
Add ARM / Apple Silicon builds

### ISSUE THREAD

**Issue by codetheweb** [svix/svix-webhooks#322]
It looks like there [might have been ARM builds in the past](https://github.com/svix/svix-webhooks/pull/245), but they were removed.
Would it be possible to add ARM builds for Apple Silicon users?

**Comment by tasn** [comment]
Yeah, I don't remember why they were removed, but I think we had an issue with building on macOS and no time to debug back then.

It's definitely the right time to revisit it though.

**Comment by svix-daniel** [comment]
This should be complete as of the merging of https://github.com/svix/svix-webhooks/pull/325.

**Comment by tasn** [comment]
Yay! I just want to merge #323, and then we'll do another release. :)
