### ISSUE TITLE
Go: support custom context 

### ISSUE THREAD

**Issue by plarsson** [svix/svix-webhooks#337]
### Motivation

Noticed a problem that the svix request didn't attach to the active trace using opentelemetry tracing (using a custom httpClient with a wrapped otelhttp transport).

The problem is that there is no way to pass in the current go context to the api functions.
I think the Svix client should support custom context. This will be useful for other use cases as well.

### Proposal

Add WithContext functions?

**Comment by tasn** [comment]
Thanks for the suggestion!
Happy to accept a PR if you know what needs to be done, otherwise we can try to prioritize it.

**Comment by plarsson** [comment]
Yes I could do that.

However it's a bit tricky without introducing breaking changes with the existing client api.  Duplicate all client functions is a bit ugly?

Not sure whats the best approach here would be?

**Comment by tasn** [comment]
Does the context have to be per call, or can we make it a configuration on the client itself? Caveat is that we'll need to create a new client every time (shouldn't be an expensive operation).

Can you maybe show how it's done in other libs?

**Comment by plarsson** [comment]
I think its a mix, I think in general for new clients, created after go 1.7 the first argument is usually always ctx. This is the go way.

AWS added another method for everything:
https://aws.amazon.com/blogs/developer/context-pattern-added-to-the-aws-sdk-for-go/
```
SendTemplatedEmail 
SendTemplatedEmailWithContext

```

Stripe added it as a parameter as they thought it was a bit too large refactoring
https://github.com/stripe/stripe-go/issues/357

Google sets it like this
https://github.com/googleapis/google-api-go-client/blob/2425be6e03d9b1fb5ccc7ee99b9a6ec776139378/appengine/v1/appengine-gen.go#L4150

Ory Kratos:
https://github.com/ory/kratos-client-go/blob/master/api_v0alpha2.go
(openapi generated)

Yours is also openapi generated but with a wrapper?

**Comment by tasn** [comment]
Yeah, we have a wrapper. Hmm... I'm tempted to just break the API as if people don't want to pass a context they can just pass `nil` right? What I'm alluding to: it's going to be a very quick fix to update the code and there aren't any 3rd party svix libs yet, so there's no dependency hell. 

What do you think?

**Comment by plarsson** [comment]
Agree I think thats the cleanest.  If context is not in scope people can pass in context.Background()

**Comment by tasn** [comment]
Whatever you think is best. :)

**Comment by tasn** [comment]
I believe this is fixed (and has been for a while).
