### ISSUE TITLE
Start using the OpenTelemetry crate for telemtry

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#344]
https://github.com/open-telemetry/opentelemetry-rust

Also: don't forget to update the docs/README to explain how to use it with datadog/newrelic/sentry.

More info / related attempts:
* https://github.com/tokio-rs/axum/issues/750
* https://github.com/tokio-rs/axum/pull/769
* https://github.com/tower-rs/tower-http/pull/180
* https://github.com/EmbarkStudios/server-framework/blob/main/src/middleware/trace/opentelemetry.rs
* Maybe https://github.com/davidB/sandbox_axum_observability

**Comment by cawfeecoder** [comment]
@tasn I think you'll get better use out of https://github.com/tokio-rs/tracing. It supports OpenTelemetry (amongst a host of other providers as well), which should give an end consumer of Svix (self-hosted) options for monitoring/observability.

**Comment by tasn** [comment]
Thanks @cawfeecoder! We are using tracing, the idea is to use the opentelemetry tracing plugin. Though thanks for the feedback, we'll check the built-in stuff in tracing too.

**Comment by tasn** [comment]
Hey @alexrejto, when would you like to have it by?

**Comment by alexrejto** [comment]
Any chance you could fit it in in the next month?

**Comment by tasn** [comment]
Unless there are surprises, I believe we can.

We'll aim to get it ready in the next couple of weeks.
