### ISSUE TITLE
Health endpoint returns 2 bytes of content causing AWS ALB to crash

### ISSUE THREAD

**Issue by alexrejto** [svix/svix-webhooks#396]
### Version
Version 0.56.0 

### Platform
AWS EC2 containers

### Description
AWS load balancer crashes when a 204 is returned with content. Since the /api/v1/health endpoint returns 2 bytes, it is not functioning as expected. I expect to see 0 bytes returned.

**Comment by tasn** [comment]
Whoops, thanks for the report! Expect a fix imminently.

**Comment by tasn** [comment]
CC @svix-dylan

**Comment by svix-dylan** [comment]
@alexrejto Thanks for bringing this to our attention! [We've just patched this on `main`](https://github.com/svix/svix-webhooks/pull/397), and plan on releasing 0.57.0 later today or tomorrow, which will include this patch.

**Comment by alexrejto** [comment]
Thanks so much for the rapid fix @svix-dylan!
Will this patch also be released to docker hub?

**Comment by svix-dylan** [comment]
@alexrejto Of course! And yes, 0.57.0 will also ship to Docker Hub.

**Comment by svix-dylan** [comment]
@alexrejto just following up to confirm v0.57.0 with this patch has shipped to Docker Hub! Apologies, this went out a little later than we’d hoped, we found some small issues in our pre-release testing we wanted to nail down. You should be good to pull the latest image to your EC2 now!

**Comment by alexrejto** [comment]
Thanks again for the speedy turn around. The fix solves the issue (which was mostly a bug in AWS)!

**Comment by tasn** [comment]
With pleasure! And yeah, I would have expected AWS to either relay verbatim or ignore the extra bytes.
