### ISSUE TITLE
Isolate test Redis keys from production values to avoid contamination.

### ISSUE THREAD

**Issue by svix-daniel** [svix/svix-webhooks#437]
This will result in junk data on a running instance and test failures if a running server is competing with the tests to receive queue tasks.

**Comment by tasn** [comment]
I think we can literally check if we are building for the test suite at compile time, and if so, add a test prefix so at least the normal workers don't conflict.

**Comment by svix-daniel** [comment]
#441 adds a test prefix, albeit not used anywhere but the one test added in that PR. If/when it's merged, other tests can add their own prefix.

**Comment by tasn** [comment]
After we do that we can also make the tests run in parallel. 😍

**Comment by tasn** [comment]
@svix-daniel, this is fixed, right? Can you please link the right PR and close this?

**Comment by svix-daniel** [comment]
Fixed in https://github.com/svix/svix-webhooks/pull/461
