### ISSUE TITLE
Optionally support datadog apm for observability and monitoring.

### ISSUE THREAD

**Issue by alexrejto** [svix/svix-webhooks#462]
## Feature Request
I see https://github.com/svix/svix-webhooks/issues/344 is also reported. However, our team has gone with datadog apm for our observability and tracing needs so it would be best for us.

https://docs.rs/datadog-apm/latest/datadog_apm/

**Comment by tasn** [comment]
Thanks @alexrejto for the suggestion!

Given that [Datadog supports OpenTelemetry](https://docs.datadoghq.com/tracing/setup_overview/open_standards/) (#44 that you mentioned), do you think adding OpenTelemetry will do the trick, or does using OpenTelemetry with Datadog come with limitations?

**Comment by tasn** [comment]
We'll look into it further. It also seems like the OpenTelemetry Rust library I mentioned above supports Datadog natively because of special extensions to OpenTelemetry.

I'll let you know once we take a look and have something to share.

**Comment by tasn** [comment]
I'm going to close this, as #344 in now fixed.

Though please reopen this if the OpenTelemetry integration is not sending everything you'd expect to datadog.
