### ISSUE TITLE
Worker: don't hold a DB connection for the whole duration

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#498]
In the worker we are getting a DB connection at the beginning of the worker, and holding it while we are making external HTTP calls that can be very slow.

This means that we are depleting our PG connection pool for no good reason. It's probably fine if the pool has a very large max connection count set, though it's terrible if the connection count is slow and will cause the server to hang.

We need to change the worker so that the connection is only held for a short duration (only when doing writes).

I'm not 100% sure this is the case. We need to figure out whether SeaORM holds the connection on `clone()`, or probably they just take the connection every time it's actually used, which means it's fine.

**Comment by tasn** [comment]
@svix-daniel, is this done?

**Comment by svix-daniel** [comment]
After some investigation, I'm pretty confident we're safe and that the connection is only held during the transaction.
