### ISSUE TITLE
Redis Client Library does not support TLS

### ISSUE THREAD

**Issue by alexrejto** [svix/svix-webhooks#528]
## Feature Request
Somewhere between a feature and a bug. I attempted to upgrade my redis cluster to require encryption in transit via TLS. redis uri of the form `rediss://<username>:<password>@<host>:<port>`

### Proposal
Change the Cargo.toml to include a tls feature for redis. From my noob internet searches it seemed like `tokio-native-tls-comp` would help.

**Comment by svix-dylan** [comment]
@alexrejto just doing some more testing on the above PR to ensure everything is in order.

**Comment by svix-dylan** [comment]
@alexrejto we've merged a patch for this! Thanks again for bringing to our attention.
