### ISSUE TITLE
Suggestion: use the error_chain create for better error handling

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#574]
We can potentially use the https://docs.rs/error-chain/latest/error_chain/ crate for better error handling and stack traces.
I'm not sure how needed it is, because with Rust most issues are enforced at compile time, but we could still have dynamo or something errors and it would be better to know where they came from.

**Comment by svix-gabriel** [comment]
Right now I'm leaning on `anyhow`, which gives us access to backtraces or manually tracing using `.with_context(...)`. It's easy to implement `From<anyhow::Error>` for our custom error type in `crate::error::Error`, but the downside is that we'd need to add `.with_context(...)` calls everywhere we want to add tracing.

I've experimented with a couple of other approaches, and the issue I keep coming back to is returning the `anyhow::Error` from an axum handler. I think that if we want to reliably and automatically capture backtraces, without using `.with_context(...)`, we need the error type that we return from our handlers to wrap an `anyhow::Error` in one way or another. I think this necessitates a non-trivial refactor of the `crate::error::Error` type.

Maybe there's another approach I'm not thinking of - I guess I want to double check that carving up the `crate:error::Error` struct to wrap an `anyhow::Error` is a reasonable approach.
