### ISSUE TITLE
Support PATCH in addition to PUT on all entities

### ISSUE THREAD

**Issue by adimyth** [svix/svix-webhooks#577]
### Version
`latest` as per dockerhub; most likely `v0.63

### Platform

docker

### Description

Suggest using `PATCH` instead of `PUT` in all the apis where we perform an update operation. It is inconvenient to pass in all the data, just to update a couple of fields. This has side-effects & can cause issues elsewhere

Example - I created an endpoint & later wished to update the URL. Using `PUT` caused all the other data fields like `events`, etc to be set to NULL.

**Comment by tasn** [comment]
I agree, we've been deferring doing this for a while, I'll see if we can get to it soon.

**Comment by tasn** [comment]
@svix-daniel, is this one done? (other than libs)

**Comment by tasn** [comment]
I'm pretty sure it's done (other than the libs which are tracked in #608 so closing this.
