### ISSUE TITLE
Making requests to endpoints without a trailing slash run forever

### ISSUE THREAD

**Issue by adimyth** [svix/svix-webhooks#578]
### Version

`latest` as per dockerhub; most likely `v0.63`

### Platform

docker

### Description

All the delete methods keep running forever. I had to manually abort them each time. This is true for all delete apis. 

In the screenshot below, notice that even after > 20s, the operation kept running. 
<img width="1073" alt="Screenshot%202022-07-23%20at%205 30 54%20PM" src="https://user-images.githubusercontent.com/26377913/180605244-3a795ef9-410d-4e16-9d7f-a488074726ac.png">

**Comment by tasn** [comment]
It's because you're missing a trailing slash in the URL... Though it's weird that it would make it run forever instead of fail!

**Comment by tasn** [comment]
Daniel, can we take a look into making these ones failures (I thought they were already).

**Comment by adimyth** [comment]
No dice! Still the same behavior

**Comment by tasn** [comment]
That's just bizzare, all of the rest of the deletions work nicely? What happens if you try deleting an application or an endpoint?

Anything else that you think may be related?

**Comment by adimyth** [comment]
Yep, the behaviour remains the same for all deletion apis. Possible reasons I can think of -

1. DB lock
2. Some triggers that are taking time to run
3. Corrupt data?
4. Cascade deletes holding up

**Comment by tasn** [comment]
It's not 2 and 4 as those aren't set. If memory serves we do soft deletes to prevent these, as there can be a lot of cascades.

1/3: maybe, not sure what could have happened. How many records do you have in the db?

**Comment by tasn** [comment]
Another thing you could do: enable "debug mode" in Postgres to show which queries are running, and then try to run the same query prefixed with `EXPLAIN ANALYZE`.

I just tested it locally (in addition to the tests testing it all the time), it works.

**Comment by adimyth** [comment]
Okay, let me give this a try

**Comment by tasn** [comment]
Please do and let us known.

**Comment by tasn** [comment]
Any news?

**Comment by adimyth** [comment]
Postgres generated the following log on deletion -

```sql
/* SQLx ping */
qlx_s_4: SELECT "application"."id", "application"."created_at", "application"."updated_at", "application"."org_id", "application"."uid", "application"."name", "application"."rate_limit", "application"."deleted" FROM "application" WHERE "application"."org_id" = $1 AND "application"."deleted" = $2 AND ("application"."id" = $3 OR "application"."uid" = $4) LIMIT $5
$1 = 'org_23rb8YdGqMT0qIzpgGwdXfHirMu', $2 = 'f', $3 = 'demo-application', $4 = 'demo-application', $5 = '1'
/* SQLx ping */
/* SQLx ping */
qlx_s_5: UPDATE "application" SET "updated_at" = $1, "uid" = $2, "deleted" = $3 WHERE "application"."id" = $4 RETURNING "id", "created_at", "updated_at", "org_id", "uid", "name", "rate_limit", "deleted"
$1 = '2022-07-26 18:09:16.775824+00', $2 = NULL, $3 = 't', $4 = 'app_2CUZ6LqM9xz4vL1wbCh6OOlEkl6'
/* SQLx ping */
```

It ran successfully when executed as a SQL query

**Comment by tasn** [comment]
Very quickly, too?

**Comment by adimyth** [comment]
Yep, in a jiffy

**Comment by tasn** [comment]
I really have no idea what it could be then. This function literally verifies the JWT (easy) and calls this query.

**Comment by adimyth** [comment]
I will retry creating the scenario & see if the issue persists

**Comment by tasn** [comment]
Thanks!

I'm closing it in the meanwhile because it looks like it's not an issue with the server, but please let me know if it is and we'll reopen it.
