### ISSUE TITLE
Passing a list of events to "List Messages" api doesn't work

### ISSUE THREAD

**Issue by adimyth** [svix/svix-webhooks#579]
### Version

v0.63

### Platform

docker

### Description

`event_types` query parameter in "List Messages" api doesn't seem to be working with a list of strings. As per the docs -
```
event_types - Array of strings or null (Event Types)
```

However, I tried the following combinations, none seem to work -

1. [user.created, user.updated]
2. ["user.created", "user.updated"]
3. [user.created]

Passing only a single element without seems to be working. Example - `event_types=user.created`

**Comment by tasn** [comment]
It's because it uses the admittedly annoying array passing format (which is default for OpenAPI): `event_types=user.created&event_types=user.updated`

**Comment by adimyth** [comment]
Super annoying tbh!!
