### ISSUE TITLE
API Endpoint for Patching an Endpoint

### ISSUE THREAD

**Issue by cjnething** [svix/svix-webhooks#618]
## Feature Request
It would be great if we could send a PATCH request to update an endpoint for certain values.

### Motivation
By using a PUT instead of a PATCH, we end up inadvertently resetting other values. For example, if I just want to update the URL for an endpoint, I don't also want to reset the description to an empty string on accident.

Thanks all!

**Comment by cjnething** [comment]
Woops! Forgot to check that this was [already in the Issues log](https://github.com/svix/svix-webhooks/issues/608), my mistake!

**Comment by tasn** [comment]
Yeah, it's a common request, we definitely need to add it already!
