### ISSUE TITLE
Typo in python sdk

### ISSUE THREAD

**Issue by bluebeel** [svix/svix-webhooks#620]
Hello,

I remarked while testing the python sdk that if we have a `eu` api token, the host used is `https://api.ei.svix.com` when it should be `https://api.eu.svix.com` 😛 
https://github.com/svix/svix-webhooks/blob/8dfb4619c86a3573b412451a64ec1dae89795905/python/svix/api.py#L823

**Comment by tasn** [comment]
OH no, great catch! Would you like to open a PR so you get the credit, or would you preferred we just fixed it ourselves?

**Comment by svix-dylan** [comment]
Hi @bluebeel! Thanks for reporting this. We've committed a patch fixing the bug (cb8a0f5f674b355da2e83cfd1af727fe936b68da) that credits you!
