### ISSUE TITLE
Document stats endpoint

### ISSUE THREAD

**Issue by SokratisVidros** [svix/svix-webhooks#628]
### Motivation

In [this changelog](https://github.com/svix/svix-webhooks/releases/tag/v0.61.0) you mentioned:

`Server: add endpoint stats endpoint for getting endpoint statistics.`

Do you have some documentation about how to use the endpoint?

**Comment by svix-dylan** [comment]
@SokratisVidros thanks for opening this! Just wanted to let you know we've published our endpoint stats endpoint, you can find documentation for it [here](https://api.svix.com/docs#tag/Endpoint/operation/get_endpoint_stats_api_v1_app__app_id__endpoint__endpoint_id__stats__get).

**Comment by tasn** [comment]
@svix-dylan, I don't think we've released a version of the libs that supports it yet, but yeah, it's documented for direct HTTP calls.

**Comment by SokratisVidros** [comment]
Thanks for the fast response!
