### ISSUE TITLE
OpenTelemetry Trace Propagation

### ISSUE THREAD

**Issue by alexrejto** [svix/svix-webhooks#631]
## Feature Request
https://github.com/svix/svix-webhooks/issues/344 added support for opentelemetry which works as expected. However, our system isn’t able to connect traces to traces emitted by our other services.

It looks like Svix is not configured to extract inbound trace propagation headers (what allows us to correlate our traces with each other)

It seems that these lines https://github.com/svix/svix-webhooks/blob/main/server/svix-server/src/main.rs#L112-L114 would need to use https://docs.rs/opentelemetry-http/0.6.0/opentelemetry_http/, like this: https://www.dynatrace.com/support/help/shortlink/opent-rust#context-propagation

Additionally, I would like to see how much time is spent in redis + postgres respectively. If those client libraries emit traces, would love to see that instrumentation as well!

### Motivation
Correlate telemetry in svix with our other web servers.

### Proposal
Update tracer to listen on inbound requests, extract context, and store it.

**Comment by svix-daniel** [comment]
Hi!

The fix that you suggest is actually already implemented [here](https://github.com/svix/svix-webhooks/blob/main/server/svix-server/src/core/otel_spans.rs#L68.)

I'm able to get some trace propagation via a test value of the `traceparent` header locally, but I understand that our setups are likely very different. To start, what format of headers are you using? The `opentelemetry` crate seems to support [the trace context format](https://www.w3.org/TR/trace-context/), as well as [baggage format](https://w3c.github.io/baggage/), however we only currently have the trace context format included right now.

Would you mind sharing examples headers and values, and where you expect the values to show up?

**Comment by alexrejto** [comment]
Hi @svix-daniel;
Benchling uses the dd-trace library which supports http headers of B3 format:
```
        X-B3-TraceId: 80f198ee56343ba864fe8b2a57d3eff7
        X-B3-ParentSpanId: 05e3ac9a4f6e3b90
        X-B3-SpanId: e457b5a2e4d86bd1
        X-B3-Sampled: 1
```
and a custom Datadog format:
``` 
      - ``x-datadog-trace-id`` the context trace id as a uint64 integer
      - ``x-datadog-parent-id`` the context current span id as a uint64 integer
      - ``x-datadog-sampling-priority`` integer representing the sampling decision.
        ``<= 0`` (Reject) or ``> 1`` (Keep)
      - ``x-datadog-origin`` optional name of origin Datadog product which initiated the request
      - ``x-datadog-tags`` optional tracer tags
```
If Opentelemetry could ingest either of these formats by default, this would be ideal but we can also extend dd-trace to support a more standard context header if necessary.

**Comment by alexrejto** [comment]
Hey after looking into this more deeply, I've found `dd-trace` is open to, and someone has even implemented, supporting W3 `traceparent` headers [here](https://github.com/DataDog/dd-trace-py/pull/3873).
My gut says we should wait for the mainline to implement this feature and this should begin working as expected.

**Comment by svix-daniel** [comment]
Would you like us to look for a solution in the meantime, or is waiting for that feature acceptable?

**Comment by alexrejto** [comment]
@svix-daniel, I think that since our library will soon implement this feature, it doesn't make sense for y'all to implement the custom datadog context headers ingestion. We can wait and thanks for implementing https://github.com/svix/svix-webhooks/pull/632.

**Comment by tasn** [comment]
@alexrejto, great, so I'm going to close this one.

We also hope to add redis tracing soon (tracked in https://github.com/svix/svix-webhooks/issues/633).
