### ISSUE TITLE
Allow deletion of archived event types

### ISSUE THREAD

**Issue by GauthierPLM** [svix/svix-webhooks#654]
### Motivation

During the development process, it is common to create and delete events based on the project needs evolution and feedback from the development. Currently, it is not possible to delete old events, these are only archived. This can be viewed when exporting an environment.

### Proposal

It would be good to be allowed to delete event types from an environment. In development this may be done easily since no end users should be relying on the environment.
In production, it would be good if it was still possible but with a big warning / a period during which the event is unused to ensure flexibility is kept while not breaking end users applications.

### Alternatives

Delete the archived events directly in the environment export and before importing it into another env.

**Comment by tasn** [comment]
Whoops, never followed up on this!

Just to clarify: the idea is to just expunge useless noise/data from test environments, right? I wonder if it makes sense to only allow it in non-production environments? What do you think?

**Comment by GauthierPLM** [comment]
I think there should be two behaviour, depending if it's a Production or Non Production env:

 - Archived data from test envs should be deletable whenever it's required by users; the risk is almost null to loose something important as it is not a prod env.
 - Archived data from prod envs should be deletable when all payloads of an event have been deleted. For example, if an event type `invoice.paid` has been archived, and the last event was sent over 90 days (default retention payload), it means this event type is no longer used and the payload no more available. The event type could be deleted without a warning. This would allow  cleaning events in case an event is no longer used and we want to make sure it disappear from every application.
  We could imagine a way to delete an event type even if payload for the said event still exist with a warning, but I don't know if there is any need for that.

Of course, having a way to delete event types in non-prod seems more useful as it's where most experiments are done.

**Comment by tasn** [comment]
Great, thanks! I think we'll at least start with deletion in development as the prod case sounds much harder and somehow less useful.

I've asked @svix-andor to take a look. Andor, one gotcha to watch out for: what happens to the app portal when viewing/editing an endpoint once an event type has been deleted? It should be fine, just need to make sure that it is!
