### ISSUE TITLE
[0.2] Python: add async variants

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#68]
We should do it if very easy to do. Otherwise it can wait for now.

**Comment by tasn** [comment]
https://github.com/openapi-generators/openapi-python-client

Both async and typing!

**Comment by tasn** [comment]
@svix-stephanie, I think we should probably just have an async variant (the same way we have `Svix()` we can have `SvixAsync()`) in the same library. At least for now.

**Comment by svix-stephanie** [comment]
Initial observation while working on other libs tickets: on the classes generated by Openapi, the methods can optionally take an async_req argument ("async_req (bool): execute request asynchronously"); it returns a thread.
