### ISSUE TITLE
[Ruby] `NameError: uninitialized constant Svix` when running tests

### ISSUE THREAD

**Issue by eric-hu** [svix/svix-webhooks#683]
### Version

    svix (0.69.0)

### Platform

 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Description

I'm running into this issue with the Svix Ruby client not loading properly in my Minitest suite.

```NameError: uninitialized constant Svix```

The tests are run using a shell script that runs `bundle exec dotenv -f ".env-test" rake test TEST=$1`. The error backtrace points to a line `Svix::Client.new(api_key)`, but this file runs fine when I require it in `bundle exec pry`. I have `require 'svix'` at the top of this file, but it still throws the error above. If I add in `require 'svix/svix'`, that particular error goes away, but then I get other ones related to Svix such as `NameError: uninitialized constant Svix::Client::Configuration`. It's almost as if https://github.com/svix/svix-webhooks/blob/main/ruby/lib/svix.rb does not actually load even when it's `require`-d.

Is this is a bug with the Svix client? Or do you have pointers on how I might debug this?

**Comment by eric-hu** [comment]
Sorry, this was user error on my part. I created a wrapper `lib/svix.rb` in my application, and it looks like this was a load path conflict, where my file took precendence over Svix webhook's one. Renaming my local file fixed the issue.

**Comment by tasn** [comment]
Thanks for the update! :)
