### ISSUE TITLE
Java SDK | Getting "eu" authentication failed even though we are passing US API token.

### ISSUE THREAD

**Issue by darshan-thakkar-1507** [svix/svix-webhooks#694]
## Bug Report
Java SDK | Getting "eu" authentication failed even though we are passing US API token.

### Version
0.69.0

### Description

We are using US environment for sending webhooks. While creating an instance of Svix we are passing **US** environment token still we are getting **_Invalid token for region "eu". (authentication_failed)_** message while performing any operations.

![image](https://user-images.githubusercontent.com/82813409/201018134-4b9bc23f-ca0d-431a-8c1c-5538d94fc7e3.png)

I debugged this code and came to know that there is a problem at 34th line , it is overriding the url at 34 which was set from 27th line.
So may be by fixing this , It might get resolved.

### Way around to resolve this 

Use below snippet to get Svix instance.

```
                SvixOptions svixOptions = new SvixOptions();
		svixOptions.setServerUrl("https://api.us.svix.com");
		Svix svix = new Svix(this.svixKey, svixOptions);
```

**Comment by svix-dylan** [comment]
@darshan-thakkar-1507 following up, the fix for this issue shipped in a library release yesterday! If you update your library to v0.70.0 it should work as expected. Thank you again!
