### ISSUE TITLE
Connection Timeout Running in Container

### ISSUE THREAD

**Issue by nkreiger** [svix/svix-webhooks#706]
## Bug Report

```
docker run -e SVIX_LOG_LEVEL="debug" -e SVIX_CACHE_TYPE="memory" -e SVIX_JWT_SECRET="x" -e DATABASE_URL="postgresql://$USER:$PASSWORD@127.0.0.1:5432/svix" docker.io/svix/svix-server:latest
```
```
docker run -e SVIX_LOG_LEVEL="debug" -e SVIX_CACHE_TYPE="memory" -e SVIX_JWT_SECRET="x" -e DATABASE_URL="postgresql://$USER:$PASSWORD@localhost:5432/svix" docker.io/svix/svix-server:latest
```

Against a database running in k8s, port-forwarded. I was able to confirm connection string with my local DB editor (DataGrip). to the exact connection string. Any ideas what I am doing wrong?

**Comment by tasn** [comment]
`localhost` and 127.0.0.1 are both pointing inside the container, you want to point to the host machine.

One easy trick is to find your LAN address and use that. Does that work?
A better solution is to use the docker `add-hosts` to add your local machine inside of the Svix docker and then connect to that.

**Comment by nkreiger** [comment]
@tasn ah you're right, I forgot it runs inside its own network (long time since I ran a stack not docker-composed), this can be closed, my bad.

**Comment by tasn** [comment]
No worries! One quick hack that may solve it too: I think there's a way to tell docker to just use the host's network device directly, instead of a private network.

**Comment by nkreiger** [comment]
@tasn for reference in case someone searches this:

```
docker run -e SVIX_LOG_LEVEL="debug" --network="host" -e SVIX_CACHE_TYPE="memory" -e SVIX_JWT_SECRET="x" -e DATABASE_URL="postgresql://$USER:$PASSWORD@$DOCKER_INTERNAL_HOST:5432/svix" docker.io/svix/svix-server:latest
```

where the host is === to `host.docker.internal`

**Comment by tasn** [comment]
Awesome, thanks a lot!

**Comment by St8Ev** [comment]
Я запустил: docker compose up у меня вывод:
![image](https://github.com/svix/svix-webhooks/assets/53135468/07f59570-9910-4294-8271-2746156999fc)
Это правильно?
