### ISSUE TITLE
Server: add OpenAPI generation

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#717]
Alternatives:
- https://github.com/tamasfe/aide
- https://github.com/juhaku/utoipa

I think `aide` looks more promising, but haven't given either a deep enough look.

**Comment by svix-andor** [comment]
Just a quick note on where this is: `aide` was integrated into svix-webhooks, so it generates a crude spec, it is missing the following still:
* [ ] Operation descriptions - #811 
* [ ] Operation summaries
* [ ] Operation IDs
* [ ] Code examples

**Comment by svix-andor** [comment]
@tasn the Python API automatically adds all of the HTTP error responses used in the API to all operations. There's no easy way to do this with aide, only by manually iterating over all operations once the API docs have been constructed and then manually adding each error response to all operations. Is this something that must be retained?

**Comment by tasn** [comment]
Can't it be part of the macro you added and just add all of them (or only a subset if defined)?

I know OpenAPI also supports a "default error", which essentially shows the structure of the error struct without specifying specific codes. To be honest, this is probably preferable if can be easily done.

**Comment by tasn** [comment]
Done.
