### ISSUE TITLE
ListOptions and PostOptions fields in Rust library should be public

### ISSUE THREAD

**Issue by ksindi** [svix/svix-webhooks#746]
[ListOptions](https://github.com/svix/svix-webhooks/blob/27dbb4ac35e6f252afbcfbcea33243bceb24f4d4/rust/src/api.rs#L126) fields in Rust library should be public otherwise they cannot be used when calling the `list` functions of their respective structs (e.g. `Application`).

I suspect we also need to do it for [PostOptions](https://github.com/svix/svix-webhooks/blob/27dbb4ac35e6f252afbcfbcea33243bceb24f4d4/rust/src/api.rs#L84).

svix version 0.73.0

**Comment by tasn** [comment]
Fixed in #747
