### ISSUE TITLE
Should use same timestamp for message signing and header timestamp(svix-timestamp header)

### ISSUE THREAD

**Issue by akash3gupta** [svix/svix-webhooks#758]
We should use same timestamp for message signing and header timestamp(svix-timestamp header)
`
Message signing code in worker.rs

        let signatures = sign_msg(
            &cfg.encryption,
            now.timestamp(),
            &body,
            &msg_task.msg_id,
            &keys,
        );`

`
Header generation code in worker.rs

        let mut headers = generate_msg_headers(
            now.timestamp(),
            &msg_task.msg_id,
            signatures,
            cfg.whitelabel_headers,
            cfg.whitelabel_header_prefix,
            endp.headers.as_ref(),
            &endp.url,
        );`

**Comment by tasn** [comment]
It's the same timestamp, it's just converting the same `now` value to a timestamp() twice (it actually just exposes the inner integer, it doesn't do much).

**Comment by akash3gupta** [comment]
Can we store current timestamp in a variable and use that variable in both lines.? 
Just to make sure that there will no difference timestamps used for message signing and timestamp header.

**Comment by tasn** [comment]
See line 260... It stores it in a variable and uses the same one in both of the lines you pointed out.

**Comment by akash3gupta** [comment]
Got it.. Thanks.
