### ISSUE TITLE
Rust ReplayIn is private but should be public

### ISSUE THREAD

**Issue by ksindi** [svix/svix-webhooks#805]
## Bug Report

Version: 0.76.0

The new replay missing struct is private and cannot be imported. It seems to be because it's not exported at pub in the api.rs file.

```
use crate::models::{
    ..., ReplayIn,
};
pub use crate::models::{
    ApplicationIn,..., SHOULD BE HERE
};
```

**Comment by tasn** [comment]
Whoops! @svix-andor, can you please take a look?

**Comment by tasn** [comment]
New version of the libs is out.
