### ISSUE TITLE
?channel query param doesn't work in list all messages

### ISSUE THREAD

**Issue by Obl3n** [svix/svix-webhooks#813]
### Version
Version 0.76.1

### Platform

Docker container, Ubuntu

### Description

```GET http://server_ip:8071/api/v1/app/application_id/msg/?channel=ANY_VALUE_HERE```

Returns ```Internal Server Error```, tried fully reinstalling databases, and application, didn't help.

In console it writes it:
```svix_server::error: type: Database("error returned from database: syntax error at or near \"ORDER\""), location: ["svix-server/src/v1/endpoints/message.rs:213"]```

#### Also, tried to use C# client library for that first, it doesn't work too
```
var messages = await svix.Message.ListAsync(application.Id, new MessageListOptions()
{
    Channel = "channe;",
});
```
Same result, throwing 
```Error calling ListMessagesApiV1AppAppIdMsgGet: {}```

**Comment by svix-gabriel** [comment]
Thanks for reporting this. We've seen this issue with other endpoints, let me see if I can fix it real quick.

**Comment by Obl3n** [comment]
Alright, take your time, thank you very much for such amazing open source solution.
