### ISSUE TITLE
CI/linting is not ran on libs when OpenAPI is changed

### ISSUE THREAD

**Issue by svix-andor** [svix/svix-webhooks#834]
## Bug Report
Changing the OpenAPI spec doesn't trigger a lint run for all libs. This is an issue because the generated code might not work with the layer we add on top. Therefore it's possible to commit OpenAPI changes which result in a broken library.

**Comment by tasn** [comment]
I think it's literally just adding the openapi.json to the paths that trigger a run, so should be easy to fix.

**Comment by svix-andor** [comment]
Resolved in #842 and #843
