### ISSUE TITLE
useNewEndpoint hook from svix-react package not working correctly

### ISSUE THREAD

**Issue by yarokon** [svix/svix-webhooks#839]
### Version

svix-react 1.4.2

### Platform

Darwin Yaroslavs-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0

### Description

1. It's impossible to create an endpoint without `filterTypes`. In this case, it's not an issue with `svix-react` (`useNewEndpoint` hook), it's in API implementation. API should allow creating endpoint with empty array. It's much easier to work with arrays when they don't convert to null when they're empty.
<img width="827" alt="Screenshot 2023-02-10 at 18 47 34" src="https://user-images.githubusercontent.com/4423716/218194982-fb693bae-344f-486b-9684-7ae0efa7b415.png">
<img width="827" alt="Screenshot 2023-02-10 at 18 47 43" src="https://user-images.githubusercontent.com/4423716/218194976-1d40ceb4-4b8c-4162-892b-a3acca1727d8.png">

2. It's very confusing how to set `filterTypes`

```ts
const { eventTypes: { setValue: setEventType }, createEndpoint } = useNewEndpoint();

setEventType(['user.signup', 'user.deleted'].map((name) => ({ name })) as EventTypeOut[]);

createEndpoint();
```

3. `useNewEndpoint` should return `createEndpoint` function which should accept endpoint payload. Why? Because if you are using form managers like `formik`, `react-hook-form`, `ant-form` you need to update values twice (the form will update the values itself, and you need manually update each value for each field)
Here is an example of how I expect it should work:

```ts
import { useNewEndpoint } from 'svix-react';
​
const { createEndpoint } = useNewEndpoint(); // should only return createEndpoint without url, description, eventTypes and rateLimitPerSecond
​
const onSubmit = async (values: { url: string; filterTypes: string[] }) => {
  await createEndpoint(values);
};
​
onSubmit({ url: 'https://example.com/webhook/', eventTypes: ['user.signup', 'user.deleted']});
```

**Comment by tasn** [comment]
Whoops, I forgot to reply. Thanks for the report, we have a fix internally and will release it soon.

Essentially: we fixed event types to receive an array of strings...

**Comment by tasn** [comment]
So actual comments:
1. You should pass `null`. Passing an empty array is invalid. We may change that at some point, but that's the current validation.
2. Fixed in an internal PR, release incoming.
3. If you want to just want to call `createEndpoint` yourself, you can just use `useSvix` to get the Svix handler and then call `svix.endpoint.create()` yourself. No need to use the React hook.
