### ISSUE TITLE
Unable to start svix-server without redis

### ISSUE THREAD

**Issue by tarunya882** [svix/svix-webhooks#870]
I am trying to run svix server without redis, but not able to run server when I remove redis. In documentation it is given redis_dsn field can be left empty but even after changing redis_dsn to empty still server is not starting and giving this error.
```
backend_1    | thread 'main' panicked at 'Invalid Redis DSN', svix-server/src/wait_for.rs:9:55
backend_1    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
server_backend_1 exited with code 101
```

**Comment by tasn** [comment]
Thanks for the report, and sorry for the delay, I missed your ticket!

You just need to remove/comment out the config var and it'll work.

I'm closing it, as it works as expected, but let me know if it doesn't and I'll reopen.

**Comment by FSMaxB** [comment]
As a workaround I made sure to set `SVIX_QUEUE_TYPE` to `memory` and set the `SVIX_REDIS_DSN` to the database URL. This way the `WAIT_FOR` waits for the database twice and then goes ahead and ignores redis.

**Comment by svix-james** [comment]
@FSMaxB , I think your diagnosis is correct. At a minimum, we should probably leave the `redis_dsn` commented out in `config.default.toml`.

**Comment by tasn** [comment]
Oh, I completely misunderstood what was going on originally. James is 100% right, we should comment out the redis dsn in the default config.
