### ISSUE TITLE
Go client verification fails if svix-signature header is an array of strings

### ISSUE THREAD

**Issue by arabello** [svix/svix-webhooks#880]
### Version
`v0.82.1`

### Platform
```
Darwin MacBook-Pro-di-buildo.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```
### Description

While verifying webhooks inside an [AWS lambda](https://pkg.go.dev/github.com/aws/aws-lambda-go@v1.28.0/lambda#Start), the [standard approach](https://pkg.go.dev/github.com/awslabs/aws-lambda-go-api-proxy@v0.13.3/core#RequestAccessorV2.EventToRequestWithContext) to get an `http.Request` from the lambda's event, creates the `svix-signature` `http.Request.Header` by splitting the original signature.

`http.Request.Header["svix-signature"]` results in an array of two strings
```go 
{"v1" "doqUF7tykdkLqUxzXTUyeoc4JIxGtOjt6kDsomething"}
```
instead of an array of a single string
```go
{"v1,doqUF7tykdkLqUxzXTUyeoc4JIxGtOjt6kDsomething"}
```

This causes the `Verify` method to fail as [it uses](https://github.com/svix/svix-webhooks/blob/9a975683f950d8762a7297d0525675d12e7a58f0/go/webhook.go#L71) calling the `http.Request.Header.Get` [returns only first value](https://pkg.go.dev/net/http#Header.Get) (in this case `v1`) instead of the two strings array.

I expected this library to support this case as using AWS lambdas is a pretty popular.

I temporary workaround it by overriding the request header
```go
req.Header.Set("Svix-Signature", strings.Join(req.Header["Svix-Signature"], ","))
```

but I expected the library to internally handle it. For example, inside the [`verify` method](https://github.com/svix/svix-webhooks/blob/9a975683f950d8762a7297d0525675d12e7a58f0/go/webhook.go#L69) there could be a check like:
```go
msgSignature := headers.Get("svix-signature")
if reflect.SliceOf(reflect.TypeOf("")) == reflect.TypeOf(headers["svix-signature"]) {
    msgSignature := strings.Join(headers["svix-signature"], ","))
}
```

**Comment by arabello** [comment]
> This feels like a bug with the AWS lambda library, as these headers are not defined as comma-separated headers

Yeah, I dug up into it: the API Gateway V2 client [is splitting _every_ header](https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/core/requestv2.go#L173-L177) considering them as comma separated. [Different behavior compared to V1](https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/core/request.go#L195-L205), though.

> What's the behavior in non lambda Go web frameworks? Any idea?

I don't have clues on other frameworks

I objectively agree that this is more an issue on the AWS client side as they are treating a custom header as a comma separated one. Actually, they are treating all headers as comma separated.

Thanks anyway, closing this

**Comment by tasn** [comment]
It's still a concern to be honest, it makes the lives of verifies more difficult if they have to workaround bad implementations. :|

**Comment by arabello** [comment]
Yeah, here the reference where I'm asking about it: https://github.com/awslabs/aws-lambda-go-api-proxy/issues/171
