### ISSUE TITLE
Operational Endpoints cannot be filtered by Operational Webhook event types

### ISSUE THREAD

**Issue by mattJDayshape** [svix/svix-webhooks#887]
### Version

0.82.1

### Platform

Linux 74d00365c75d 5.10.102.1-microsoft-standard-WSL2 x86_64 GNU/Linux

### Description

Unable to specify which operational webhook events to subscribe/filter to. The API rejects a request to add an event filter to an operational webhook endpoint with an `HTTP 422`  when you try to add a event, (e.g. `message.attempt.failing` ) stating that:
"The following event types don't exist: `message.attempt.failing`"

The API request body I sent to `POST https://my.svix.address.goes.here/api/v1/app/{app_id}/endpoint/` used is here:

```
{
    "url": "https://any.old.url/srsly",
    "version": 1,
    "filterTypes": [
        "message.attempt.failing",
        "message.attempt.exhausted"
    ]
}

```

You should be able to specify the names of operational webhooks as `filterTypes` when creating OR updating an operational endpoint.

**Comment by svix-james** [comment]
@tasn A migration would be nice, but there's not a clean way to specify the appropriate org-id in a migration, is there? I'm not sure it's safe to assume that the 'default' org-id is the one that will be used in all cases.

**Comment by svix-james** [comment]
Scratch the previous. I'll write the migrations using the hard-coded "management" org-id.
