### ISSUE TITLE
Can Svinx be compatible with ubuntu 22.04?

### ISSUE THREAD

**Issue by Galactic21** [svix/svix-webhooks#901]
Good afternoon, i saw your [dockerfile](https://github.com/svix/svix-webhooks/blob/main/server/Dockerfile) and im wonder if a can use ubuntu 22.04 image instead of debian:11.2-slim in Production section.

Cheers.

**Comment by tasn** [comment]
Hey. It should just work, feel free to change it locally and build it. Though why does it matter to you?

**Comment by Galactic21** [comment]
Hey @tasn , usually when I implement a service in my infrastructure, I use an Ubuntu 22.04 image and I was just wondering about compatibility. 
Thank you for your attention.
Best regards.
