### ISSUE TITLE
Rust client does not pass supported query param format for arrays

### ISSUE THREAD

**Issue by ksindi** [svix/svix-webhooks#921]
## Bug Report

Chatted with @tasn and it looks like the Rust client library is passing in array query params as comma separate (e.g. `?event_types=a,b,c`) which Svix doesn't support.

### Version

0.85.1

### Platform

Linux: 5.19.0-41-generic

### Description

Code reproduction:
```
use svix::api::{MessageListOptions, Svix};

// Create an async main function
#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let app_uid = "somei-id";

    // Create a new Svix client
    let svix = Svix::new("REDACTED".to_string(), None);

    let event_types = vec![
        "card_transaction.updated".to_string(),
        "dispute.updated".to_string(),
    ];

    println!("event_types: {:?}", event_types);

    let options = MessageListOptions {
        event_types: Some(event_types),
       ..Default::default()
    };

    let result = svix
        .message()
        .list(app_uid.to_string(), Some(options))
        .await?;

    println!("got value from the server; result={:?}", result);

    Ok(())
}
```

I get the error:
```
Error: Varidation error Some(HttpValidationError { detail: [ValidationError { loc: ["query", "__all__"], msg: "String must match the following pattern: [a-zA-Z0-9\\-_.].", _type: "value_error" }] })
```

**Comment by tasn** [comment]
Just to add more context: the problem is with the OpenAPI generator. We can try just updating the generator maybe it's fixed, or alternatively we need to override the template to do it correctly.
The current implementation is really quite silly, it doesn't even escape `,`, it just concatenates the array members with commas in between.
