### ISSUE TITLE
JS SDK missing `with_content` parameter on `v1.message.list` endpoint

### ISSUE THREAD

**Issue by TimeToogo** [svix/svix-webhooks#942]
## Bug Report

https://api.svix.com/docs#tag/Message/operation/v1.message.list

### Version

`0.85.1`

### Platform

All

### Description

I tried this code:

```
const messages = await svix.message.list(
      "app_...",
      {
        withContent: true
      }
    );
```

I expected to see this happen see the `messages` contain the webhook `payload` but they did not.

**Comment by tasn** [comment]
Oh, you're right! It looks like the new parameter wasn't added to the libs. We'll take a look this week.
