### ISSUE TITLE
(Ruby) Svix::ApiError Error in the HTTP2 framing layer

### ISSUE THREAD

**Issue by rolznz** [svix/svix-webhooks#964]
### Version

0.85.1 (Ruby)

### Platform

Debian 5.10.136-1~deb10u3 (2022-09-06)(5.10.0-0.deb10.17-amd64)

### Description

~~After updating Svix to 0.85.1 from 0.82.1 we sometimes see an error being reported when `SVIX_CLIENT.message.create` is called.~~ Edit: the error seems more about concurrent usage or increased traffic on the server rather than a specific Svix version.

```
Svix::ApiError
Error in the HTTP2 framing layer
HTTP status code: 0
```

**Comment by tasn** [comment]
Whoops, interesting. And it doesn't happen with 0.82.1 at all? Even if you downgrade back now?

I wonder if we also updated a dependency that made it fail.

**Comment by rolznz** [comment]
@tasn we will downgrade and let you know if the issue persists or not.

**Comment by tasn** [comment]
Thanks! Let me know and we'll start investigating. The reason why we need this verification is that it only happens sometimes which means it'll be hard to reproduce.

Btw, please *only* downgrade Svix (and whatever dependencies it'll autodowngrade), so that we can make sure it's just the Svix version change that caused it.

**Comment by rolznz** [comment]
@tasn Sorry for the delay. I have downgraded only Svix but the change hasn't been deployed yet. I will keep you updated.

**Comment by rolznz** [comment]
@tasn unfortunately the downgrade didn't fix it. It must have been some of the other changes that also went in the same release.

Thanks for the support!

**Comment by tasn** [comment]
With pleasure. Let me know if there's anything we can do to help!

**Comment by rolznz** [comment]
@tasn we are wondering if it is because we create a static client rather than one client per request. Do you recommend creating a new client for each request, or is it able to handle multiple requests simultaneously?

**Comment by tasn** [comment]
Let me reopen this then.

Some people do a client per request, some a long-lived, it varies. I don't know how many do either in Ruby. Are you able to reproduce it with reusing a client but not when creating one per request?

**Comment by rolznz** [comment]
@tasn thanks. I will let you know once we have deployed the change and confirmed if the issue improves or not

**Comment by tasn** [comment]
Thanks!

**Comment by tasn** [comment]
OK, thanks, and weird! What version of Ruby are you using? Not the svix lib, actual Ruby.

**Comment by rolznz** [comment]
@tasn my apologies - the change hadn't been deployed yet. It's now deployed and we are currently monitoring.

We are using Ruby 3.2

**Comment by amerritt14** [comment]
> @tasn we are wondering if it is because we create a static client rather than one client per request. Do you recommend creating a new client for each request, or is it able to handle multiple requests simultaneously?

My solution for a rails app was to monkeypatch `Svix::Client` in an initializer so that every call to `Svix::Client` creates a new request.

```
# config/initializers/svix.rb
# This is monkey patching the Svix gem to allow us to set the API key without passing it in as an argument
# Since they don't have a way to add it in a configure block.
# This allows us to do `Svix::Client.method` in the app
# instead of `Svix::Client.new(ENV["SVIX_AUTH_TOKEN"]).method`
module Svix::Client::MonkeyPatch
  delegate_missing_to :new_client

  def new_client
    @new_client ||= new(ENV["SVIX_AUTH_TOKEN"])
  end
end

Svix::Client.extend Svix::Client::MonkeyPatch
```

**Comment by rolznz** [comment]
Just an update from my side: creating a new Svix client for each request didn't help us, we're still getting the HTTP2 error occasionally.

**Comment by tasn** [comment]
I believe we already have retries in the library, though maybe only on 5xx and not on general networking issues? This is the code that does it: https://github.com/svix/svix-webhooks/blob/main/ruby/templates/api_client_typhoeus_partial.mustache#L12

I'd love it if you could contribute a fix for it!

**Comment by rolznz** [comment]
@tasn we updated to use the fix above on October the 11th. Since then we have had no more occurrences of these errors.  Thank you! :tada:

**Comment by tasn** [comment]
Yay! :)

Sorry for missing your response!
